name: Release app

on:
  workflow_dispatch:

jobs:
  release:
    name: Release app
    runs-on: ubuntu-latest

    steps:
      - name: Build app
        uses: ./.github/workflows/build.yml

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages

      - name: Release app on GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: packages/**/*