name: Build, package & release app

on:
  workflow_dispatch:

jobs:
  package:
    name: Package app
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build packages
        id: build
        run: ./gradlew packageReleaseDistributionForCurrentOS --no-daemon
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
          VERCORS_API_KEY: ${{ secrets.VERCORS_API_KEY }}
          VERCORS_API_URL: ${{ secrets.VERCORS_API_URL }}
        continue-on-error: true

      - name: Check packaging errors
        if: steps.build.outcome != 'success'
        run: cat launcher/app/build/compose/logs/**/*-err.txt && exit 1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.os }}
          path: launcher/app/build/compose/binaries/main-release/**/*

  release:
    name: Release app
    runs-on: ubuntu-latest
    needs: package

    steps:
      - name: Build app
        uses: ./.github/workflows/build.yml

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages

      - name: Release app on GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: packages/**/*